import { readFileSync, writeFileSync } from 'fs';
const f = 'D:/FILES/project/KomuniPH/web/js/profile.js';
const lines = readFileSync(f, 'utf8').split('\n');
const before = lines.slice(0, 270);
const after = lines.slice(333);
const n = [];
n.push("  const memberSince = profile.created_at");
n.push("    ? new Date(profile.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })");
n.push("    : 'Recently joined';");
n.push("  return `"); 
n.push('    <div class="profile-frame" style="${themeStyle}; ${bgStyle}">');
n.push('      <div class="profile-banner" style="${bgStyle}">');
n.push('        <div class="profile-banner-inner">');
n.push('          <h1 style="color: ${textColor}; margin: 0; font-size: 1.25rem;">KomuniPH Profile</h1>');
n.push('        </div>');
n.push('      </div>');
n.push('      <div class="profile-title">');
n.push('        <h2>${escapeHtml(fullName)}</h2>');
n.push("        ${nickname ? `<p class=\"profile-nickname\">\"${escapeHtml(nickname)}\"</p>` : ''}");
n.push('      </div>');
n.push('      <nav class="profile-nav">');
n.push('        <a href="#/home">Home</a>');
n.push('        <a href="#/profile">Profile</a>');
n.push('        <span class="nav-disabled" title="Coming soon">Connections</span>');
n.push('        <span class="nav-disabled" title="Coming soon">Photos</span>');
n.push('        <a href="#/messages">Messages</a>');
n.push('      </nav>');
n.push('      <div class="profile-status">');
n.push('        <span>Member since ${memberSince}</span>');
n.push('      </div>');
n.push('      <main class="profile-content">');
n.push('        <section class="profile-main">');
n.push('          <div class="profile-module">');
n.push('            <div class="profile-module-header">');
n.push('              <span>Profile</span>');
n.push('              <span style="font-size: 0.75rem;">&#9825;</span>');
n.push('            </div>');
n.push('            <div class="profile-module-body">');
n.push('              <div style="display: flex; gap: 1rem;">');
n.push('                <div style="flex-shrink: 0;">');
n.push('                  ${profile.profile_photo_url');
n.push('                    ? `<img src="${escapeHtml(profile.profile_photo_url)}" alt="Profile" class="profile-photo-img">`');
n.push('                    : `<div class="profile-photo-initials">${escapeHtml((firstName || displayName || username).charAt(0).toUpperCase())}</div>`}');
n.push('                </div>');
n.push('                <div style="flex: 1;">');
n.push('                  <div style="font-weight: 600; font-size: 1rem; color: var(--theme-text);">${escapeHtml(fullName)}</div>');
n.push('                  <div style="font-size: 0.875rem; color: var(--theme-text-secondary);">@${escapeHtml(username)}</div>');
n.push("                  ${nickname ? `<div style=\"font-size: 0.75rem; font-style: italic; color: var(--theme-text-secondary); margin-top: 0.25rem;\">\"${escapeHtml(nickname)}\"</div>` : ''}");
n.push('                  <div style="font-size: 0.75rem; color: var(--theme-text-secondary); margin-top: 0.5rem;">${memberSince}</div>');
n.push('                  <div style="margin-top: 0.75rem;">');
n.push('                    <a href="#/messages?user=${escapeHtml(username)}" class="btn btn-secondary" style="font-size: 0.75rem; padding: 0.25rem 0.75rem;">Message</a>');
n.push('                  </div>');
n.push('                </div>');
n.push('              </div>');
n.push('            </div>');
n.push('          </div>');
