n.push('          <div class="profile-module">');
n.push('            <div class="profile-module-header">');
n.push('              <span>About Me</span>');
n.push('              <span style="font-size: 0.75rem;">&#9825;</span>');
n.push('            </div>');
n.push('            <div class="profile-module-body">');
n.push('              <div class="profile-info-grid">');
n.push('                <span class="profile-info-label">First Name</span>');
n.push('                <span class="profile-info-value">${escapeHtml(firstName)}</span>');
n.push("                ${middleName ? `"); 
n.push('                <span class="profile-info-label">Middle Name</span>');
n.push('                <span class="profile-info-value">${escapeHtml(middleName)}</span>` : \'\'}');
n.push('                <span class="profile-info-label">Last Name</span>');
n.push('                <span class="profile-info-value">${escapeHtml(lastName)}</span>');
n.push("                ${nickname ? `"); 
n.push('                <span class="profile-info-label">Nickname</span>');
n.push('                <span class="profile-info-value">${escapeHtml(nickname)}</span>` : \'\'}');
n.push('                <span class="profile-info-label">Display Name</span>');
n.push('                <span class="profile-info-value">${escapeHtml(displayName)}</span>');
n.push('              </div>');
n.push("              ${bioValue ? `"); 
n.push('              <div style="margin-top: 1rem; padding-top: 0.75rem; border-top: 1px solid var(--theme-card-border-color);">');
n.push('                <div class="profile-info-label" style="margin-bottom: 0.25rem;">Bio</div>');
n.push('                <div class="profile-info-value" style="font-size: 0.875rem; white-space: pre-wrap;">${escapeHtml(bioValue)}</div>');
n.push('              </div>` : \'\'}');
n.push('            </div>');
n.push('          </div>');
n.push('          <div class="profile-module">');
n.push('            <div class="profile-module-header">');
n.push('              <span>Photos</span>');
n.push('              <span style="font-size: 0.75rem;">&#9825;</span>');
n.push('            </div>');
n.push('            <div class="profile-module-body">');
n.push('              <div class="coming-soon">Photo gallery coming soon</div>');
n.push('            </div>');
n.push('          </div>');
n.push('        </section>');
n.push('        <aside class="profile-sidebar">');
n.push('          <div class="sidebar-module">');
n.push('            <div class="sidebar-module-header">Friends</div>');
n.push('            <div class="sidebar-module-body">');
n.push('              <div class="coming-soon">No connections yet</div>');
n.push('            </div>');
n.push('          </div>');
n.push('          <div class="sidebar-module">');
n.push('            <div class="sidebar-module-header">Community</div>');
n.push('            <div class="sidebar-module-body">');
n.push('              <div class="coming-soon">Community features coming soon</div>');
n.push('            </div>');
n.push('          </div>');
n.push('          <div class="sidebar-module">');
n.push('            <div class="sidebar-module-header">Featured</div>');
n.push('            <div class="sidebar-module-body">');
n.push('              <div class="coming-soon">Featured content coming soon</div>');
n.push('            </div>');
n.push('          </div>');
n.push('        </aside>');
n.push('      </main>');
n.push('      <section class="profile-comments">');
n.push('        <div class="profile-module">');
n.push('          <div class="profile-module-header">');
n.push('            <span>Comments</span>');
n.push('            <span style="font-size: 0.75rem;">&#9825;</span>');
n.push('          </div>');
n.push('          <div class="profile-module-body">');
n.push('            <div class="coming-soon">Comments coming soon</div>');
n.push('          </div>');
n.push('        </div>');
n.push('      </section>');
n.push('      <div class="profile-actions">');
n.push('        <button class="btn btn-secondary" id="edit-profile-btn" onclick="window.startEditProfile()">Edit Profile</button>');
n.push('        <button class="btn btn-primary" id="customize-profile-btn" onclick="window.openCustomization()">Customize Profile</button>');
n.push('      </div>');
n.push('    </div>');
n.push('    <div id="profile-edit" style="display:none">`);');
